package cn.com.wowgz.face_attendance_system.entitiy;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table class_info
 */
public class ClassInfo implements Serializable {

    private Integer id;
    private String classNumber;
    private String classPopulation;
    private String classMonitor;
    private String classAcademy;
    private static final long serialVersionUID = 1L;
    public Integer getId() {
        return id;
    }
    public void setId(Integer id) {
        this.id = id;
    }
    public String getClassNumber() {
        return classNumber;
    }

    public void setClassNumber(String classNumber) {
        this.classNumber = classNumber == null ? null : classNumber.trim();
    }

    public String getClassPopulation() {
        return classPopulation;
    }

    public void setClassPopulation(String classPopulation) {
        this.classPopulation = classPopulation == null ? null : classPopulation.trim();
    }

    public String getClassMonitor() {
        return classMonitor;
    }

    public void setClassMonitor(String classMonitor) {
        this.classMonitor = classMonitor == null ? null : classMonitor.trim();
    }

    public String getClassAcademy() {
        return classAcademy;
    }

    public void setClassAcademy(String classAcademy) {
        this.classAcademy = classAcademy == null ? null : classAcademy.trim();
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", classNumber=").append(classNumber);
        sb.append(", classPopulation=").append(classPopulation);
        sb.append(", classMonitor=").append(classMonitor);
        sb.append(", classAcademy=").append(classAcademy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}